name: sanmill
description: A new Flutter project.

version: 0.18.0+1446

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  audioplayers: ^0.14.0
  path_provider: ^1.6.1
  package_info: ^0.4.0+16
  uuid: ^2.0.4
  url_launcher: ^5.7.10
  intl: ^0.17.0
  flutter_socket_io: ^0.6.0
  catcher: ^0.4.1
  stack_trace: ^1.9.6
# sentry_flutter: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true  

  assets:
    - images/logo.png
    - assets/audios/draw.mp3
    - assets/audios/fly.mp3
    - assets/audios/go.mp3
    - assets/audios/illegal.mp3
    - assets/audios/lose.mp3
    - assets/audios/mill.mp3
    - assets/audios/place.mp3
    - assets/audios/remove.mp3
    - assets/audios/select.mp3
    - assets/audios/win.mp3

flutter_intl:
  enabled: true
