name: sanmill
description: A new Flutter project.

version: 0.19.0+1540

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.7.0
  path_provider: ^2.0.1
  package_info: ^2.0.0
  uuid: ^3.0.1
  url_launcher: ^6.0.2
  intl: 0.17.0
  animated_text_kit: ^4.0.0
  flutter_colorpicker: ^0.4.0-nullsafety.0
  catcher:
    git:
      url: https://github.com/jhomlala/catcher
      ref: feature/nullsafety
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true  

  assets:
    - images/logo.png
    - assets/audios/draw.mp3
    - assets/audios/fly.mp3
    - assets/audios/go.mp3
    - assets/audios/illegal.mp3
    - assets/audios/lose.mp3
    - assets/audios/mill.mp3
    - assets/audios/place.mp3
    - assets/audios/remove.mp3
    - assets/audios/select.mp3
    - assets/audios/win.mp3

flutter_intl:
  enabled: true
