name: mill
version: 3.1.0
summary: A Mill Game which supports many rule variants.
description: |
  Nine men's morris is a strategy board game for two players
  dating at least to the Roman Empire. The game is also
  known as nine-man morris, mill, mills, the mill game,
  merels, merrills, merelles, marelles, morelles, and
  ninepenny marl in English.

  **Rules:**

  * A player who aligns three of his pieces on a board line
    has a mill and may remove his opponent's piece(s).
  * Any player reduces to two pieces and has no option to
    form new mills and thus loses the game.
  * A player can also lose with more than three pieces
    if his opponent blocks them not to be moved.

  _More build details: https://github.com/calcitem/Sanmill.git_

grade: stable
confinement: strict
base: core18
license: 'GPL-3.0'

apps:
  mill:
    command: usr/local/bin/mill
    extensions: [flutter-stable]
    plugs: [home]

parts:
  mill:
    plugin: flutter
    source: .
    build-packages: [git, g++-8, libstdc++6]
    stage-packages: [g++-8, libstdc++6]
    override-build: |
      ./flutter-init.sh
      flutter config --enable-linux-desktop
      cd src/ui/flutter_app
      flutter create --platforms=linux .
      flutter clean
      flutter build linux --release -v
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/bin
      cp -r build/linux/x64/release/bundle/* ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/

