name: Qt on Windows

on:
  push:
    branches: [release]
    paths:
      - 'src/ui/qt/**'
      - 'src/*'
      - 'src/perfect/**'
  pull_request:
    types: [review_requested, ready_for_review]
    paths:
      - 'src/ui/qt/**'
      - 'src/*'
      - 'src/perfect/**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup VS
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          setup-python: 'true'
          tools: 'tools_cmake'
          set-env: 'false'
          tools-only: 'false'
          aqtversion: '==3.1.7'
          py7zrversion: '==0.16.1'
          extra: '--external 7z'

      - name: Build Qt with CMake
        run: |
          cd src/ui/qt
          cmake . -DCMAKE_PREFIX_PATH="D:\\a\\Sanmill\\Qt\\5.15.2\\msvc2019_64"
          cmake --build . --target mill-pro --config Release

      - name: Archive Qt
        uses: actions/upload-artifact@v3
        with:
          name: mill-pro
          path: src/ui/qt/release/mill-pro.exe
