name: Snapcraft

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Snapcraft Build
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Install LXD
        run: |
          sudo snap install lxd
          sudo lxd init --auto

      - name: Add GitHub Actions user to the lxd group
        run: |
          sudo usermod -aG lxd $USER
          newgrp lxd

      - name: Build snap using LXD
        run: snapcraft --use-lxd

      - name: List Snap Files
        run: ls -la *.snap

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: '*.snap'

      - name: Install Snap Locally
        run: |
          sudo snap install --dangerous *.snap
